name: Build Qt Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    env:
      BUILD_DIR: 'build/${{ github.run_id }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qt
        run: |
          choco install qt5 --limit-output
          echo "C:\Qt\5.15.2\msvc2019_64\bin" >> $Env:GITHUB_PATH

      - name: Install build dependencies
        run: |
          choco install visualstudio2019buildtools --limit-output

      - name: Build project
        run: |
          mkdir $env:BUILD_DIR
          cd $env:BUILD_DIR
          qmake ..\..\path\to\OOPM.pro
          nmake

      - name: Move executable to build directory
        run: |
          Move-Item -Path .\OOPM.exe -Destination $env:BUILD_DIR\OOPM.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qt-build-${{ github.run_id }}
          path: ${{ env.BUILD_DIR }}

      - name: Commit and push build artifacts
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $env:BUILD_DIR\*
          git commit -m "Add build artifacts from run ${{ github.run_id }}"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
